spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8000
  error:
    include-binding-errors: always
    include-message: always
logging:
  level:
    org:
      springframework:
        test:
          context:
            support:
              AbstractContextLoader: WARN
              AnnotationConfigContextLoaderUtils: WARN
