name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build And Deploy Spring boot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 #checkout code

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests #run unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application  #build applications
        run: |
          mvn clean 
          mvn -B package --file pom.xml
          
